version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "master"
    reviewers:
      - "OpenNMS/dependabot-reviewers-maven"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
