= Linux

To install {page-component-title} on your Linux system you have to install a current Java Runtime Environment link:http://openjdk.java.net[OpenJDK 8] or link:https://developer.oracle.com/java[Oracle 8 JRE]

Download and extract the latest stable release from link:https://github.com/OpenNMS/opennms-provisioning-integration-server/releases/latest[GitHub].

TIP: The provided system start scripts assume you install {page-component-title} in `/opt/opennms-pris`.
     If you want to install in a different directory, ensure you modify the start scripts to fit your location.

NOTE: Make sure your `java` binary is in your search path.

[source, bash]
----
# Create directory for PRIS
mkdir /opt/opennms-pris
cd /opt/opennms-pris

# Download latest release from GitHub
curl -L {{% ghlatesturl "https://api.github.com/repos/OpenNMS/opennms-provisioning-integration-server/releases/latest" ".tar.gz" %}} -o pris-latest.tar.gz

# Extract in current directory
tar xzf pris-latest.tar.gz --strip-components=1
----

== Systemd Start Script

To start {page-component-title} as a system service on a Linux system using Systemd you can use the init script

[source, bash]
----
# Current working directory as root: /opt/opennms-pris

cp opennms-pris.init /etc/init.d/opennms-pris
update-rc.d opennms-pris defaults
service opennms-pris start
----

== SysV Init Script

To start {page-component-title} as a system service on a Linux system using SysV you can use the init script

[source, bash]
----
# Current working directory as root: /opt/opennms-pris

cp opennms-pris.service /etc/systemd/system
systemctl enable opennms-pris.service
systemctl start opennms-pris.service
----

== Run in Foreground

Use this command to start {page-component-title} in foreground:

[source, bash]
----
# Current working directory: /opt/opennms-pris
java -cp ./lib/*:./opennms-pris.jar org.opennms.pris.Starter
----
