[[scripts]]
== Script Steps
After the mapper has delivered its requitition multiple script steps can be used to customize the result.
This script steps can change the requisition initially provided by the mapper.
Script steps provide a requisition as there result, what allows the chaining of script steps.
Every script step has access to the latest version of the requisition.
The first script steps reads the requisition from the mapper.
The second script step reads the requisition privided by the first script step and so on.
Additionally every script step can access the configuration of PRIS and the raw result of the source.
The script will be executed by Apache-BSF. There for all Apache-BSF supported languages can be used to write script steps.
By default runtimes for Groovy 2.3.3 and Beanshell 2.0b5 are provided out of the box.

Script steps are configured in the `requisition.properties` for the requisition.

----
/opt/opennms-pris
└── requisitions
|   └── myRequisitionConfiguration
|       └── requisition.properties
└── scriptsteps
    └── default
    |   └── reverseDNS.groovy
    |   └── requisitionRename.groovy
    |   └── IgnoreNodeByCategory.groovy
    └── custom
        └── myScript.groovy
----

.How to add script steps
[source,bash]
----
### File: requisition.properties

## source configuration part
source = ...

## Run a no operation mapper
mapper = echo

# run script step
script.file = ../../scriptsteps/default/requisitionRename.groovy, ../../scriptsteps/default/IgnoreNodeByCategory.groovy
----

.Example script step 1
[source,java]
----
include::{docdir}/configs/scriptsteps/default/requisitionRename.groovy[]
----

.Example script step 2
[source,java]
----
include::{docdir}/configs/scriptsteps/default/IgnoreNodeByCategory.groovy[]
----

.Example script step 3
[source,java]
----
include::{docdir}/configs/scriptsteps/default/reverseDNS.groovy[]
----

.Example script step 4
[source,java]
----
include::{docdir}/configs/scriptsteps/default/failOnEmpty.groovy[]
----

Every script step can reference variable from the runtime of PRIS. The following script shows the provided objects:

.Example script step 5
[source,java]
----
include::{docdir}/configs/scriptsteps/default/sample.groovy[]
----

Every script step has to provide a Requisition object as its result.
For every request of a requisition each script step is reloaded.
