---
title: Provision to OpenNMS
chapter: false
weight: 40
---

To use the requisition from _PRIS_ in _OpenNMS_ you have the following possibilities:

* Use Provisiond cron jobs and import from _PRIS_ in scheduled interval
* Trigger an Event into _OpenNMS_ to import nodes from a given _PRIS URL_.

== Provisiond scheduled

_Provisiond_ can be configured to provision a requisition from an `URL` on a configurable schedule.
To configure _Provisiond_ to provision a requisition from _PRIS_ via `http` a configuration entry like the following can be used.

.Configuration from OpenNMS Provisiond with provisiond-configuration.xml
[source,xml]
----
<requisition-def import-name="myRouter" import-url-resource="http://localhost:8000/requisitions/myRouter">
  <cron-schedule>0 0 0 * * ? *</cron-schedule>
</requisition-def>

<requisition-def import-name="myServer" import-url-resource="http://localhost:8000/requisitions/myServer">
  <cron-schedule>0 0 1 * * ? *</cron-schedule>
</requisition-def>
----

== Provision via Event

A special _OpenNMS Event_ can be sent to _OpenNMS_ to trigger provisioning of a requisition right away.
Sending an event to _OpenNMS_ in general can be achieved via the _ReST API_ or the _send-event.pl_ script.

The following example uses `curl` using the ReST API:

[source, bash]
----
curl -u admin -X POST -d \
  "<event><uei>uei.opennms.org/internal/importer/reloadImport</uei> \
     <parms><parm> \
         <parmName>url</parmName><value>http://${PRIS_URL}:8000/requisitions/${REQUISITION}</value> \ <1>
     </parm></parms> \
   </event>" \
   -H "Content-Type: application/xml" http://${OPENNMS_IP}:8980/opennms/rest <2>
----
<1> Replace the ${PRIS_URL} with the IP and port where you have _PRIS_ running, replace ${REQUISITION} with the name of the requistion you want to import
<2> Replace the ${OPENNMS_IP} with the IP or host name of your _OpenNMS_ instance

The following example demonstrates the use of _send-event.pl_ to emit the provisioning event.

{{% notice info %}}
If you want to send the _Event_ from a remote system, consider the TCP port 5817 is by default just listening on local loopback interface.
Opening the service to the network is a security risk, cause the communication is unauthenticated and plain text and strongly advice to use the ReST API with HTTPS instead.
{{% /notice %}}

[source, bash]
----
./send-event.pl -p 'url http://localhost:8000/requisitions/myRouter' uei.opennms.org/internal/importer/reloadImport
----

