---
title: Script Steps
chapter: false
weight: 30
chapter: false
---

After the mapper has delivered its requitition, multiple script steps can be used to customize the result.
These script steps can change the requisition initially provided by the mapper.
Script steps provide a requisition as their results, which allows the chaining of script steps.
Every script step has access to the latest version of the requisition.
The first script step reads the requisition from the mapper.
The second script step reads the requisition provided by the first script step and so on.
Additionally every script step can access the configuration of _PRIS_ and the raw result of the source.
The script steps are executed by the JVM following the JSR-223 specification. Therefore all JSR-223 supported languages can be used to write script steps.
By default runtimes for Groovy 2.3.3 and Beanshell 2.0b5 are provided out of the box.

Every script step has to provide a Requisition object as its result.
For every request of a requisition each script step is reloaded.

Script steps are configured in the `requisition.properties` for the requisition.

----
/opt/opennms-pris
└── requisitions
|   └── myRequisitionConfiguration
|       └── requisition.properties
└── scriptsteps
    └── default
    |   └── reverseDNS.groovy
    |   └── requisitionRename.groovy
    |   └── IgnoreNodeByCategory.groovy
    └── custom
        └── myScript.groovy
----

.How to add script steps
[source,bash]
----
### File: requisition.properties

## source configuration part
source = ...

## Run a no operation mapper
mapper = echo

# run script step
script.file = ../../scriptsteps/default/requisitionRename.groovy, ../../scriptsteps/default/IgnoreNodeByCategory.groovy
----

.Example script step 1
[source,java]
----
include::static/configs/scriptsteps/default/requisitionRename.groovy[]
----

.Example script step 2
[source,java]
----
include::static/configs/scriptsteps/default/IgnoreNodeByCategory.groovy[]
----

.Example script step 3
[source,java]
----
include::static/configs/scriptsteps/default/reverseDNS.groovy[]
----

.Example script step 4
[source,java]
----
include::static/configs/scriptsteps/default/failOnEmpty.groovy[]
----

.Example script step 5
[source,java]
----
include::static/configs/scriptsteps/default/OpenNMS_Assets_1_12.groovy[]
----

Every script step can reference variables from the runtime of _PRIS_. The following script shows the provided objects:

.Example script step 6
[source,java]
----
include::static/configs/scriptsteps/default/sample.groovy[]
----

The following two script steps provide a mechanism to fail the requisition on purpose if the amount of nodes has changed to drastically to the previous run.
The setup contains of two scripts that have to be included as script steps in order.

.Example script step 7
[source,java]
----
include::static/configs/scriptsteps/default/failOnSizeChange.groovy[]
----

The persistence of the previous requistion size is provided by the second script step of the setup.

.Example script step 8
[source,java]
----
include::static/configs/scriptsteps/default/persistRequisitionSize.groovy[]
----

.Example script step 9
[source,java]
----
include::static/configs/scriptsteps/default/selectNodeByCategory.groovy[]
----
