
[[script-source]]
=== Script Source
This source is build to give you the flexibility building your own source without the need compiling from source.
The source uses https://www.jcp.org/en/jsr/detail?id=223[JSR-223 Scripting Engine].
The used language can be changed by setting the property `source.lang` in your `requisition.properties` file.

[options="header"]
|========================
| Parameter       | Required | Description
| `source`        |    *     | `script` to use JSR-223 Script Engine as source
| `source.file`   |    *     | Path to script source relative to `requisition.properties`
| `source.lang`   |          | JSR-223 Script language by name, by default the file extension is used to detect the language.
| `source.<name>` |          | You can have access to a parameter `name` in your Groovy script if you name it with the prefix `source.`
|========================

You can find a working Groovy source in the `examples/source/scriptExample` directory.
A custom parameter name `count` is passed into the Groovy script.

.Example configuration to generate a requisition from a Groovy script
[source,bash]
----
include::../examples/source/scriptExample/requisitions/myGroovySource/requisition.properties[]
----
