= CSV Source

The `xls` source can also create a requisition from a UTF-8 encoded comma separated variable (CSV) file if the given file name has the `.csv` suffix.

In this case the first line of the csv file should contain a comma separated list of headers in the same way the spreadsheet should be configured in a normal xls source. 
Alternatively, a property can be set containing comma separated set of headers to be is used as the first line of the csv file.
This allows csv file to be raad which don't have a header line.

[options="header",autowidth"]
|===
| Parameter         | Required | Description
| `source`          | *        | set `xls` to use the XLS source for this requisition
| `source.file`     | *        | path of the CSV file to read relative to the `requisition.properties`.Note the file name must end with `.csv`
| `source.org.opennms.pris.spreadsheet.fields` |          | If this property is not present, the first line of the csv file is used as the column headers in the same way as in the xls data source. 
If this property is set, value of this field should be a comma separated set of headers to be used instead of using the first line of the csv file.
|===

The structure of the csv file should follow the same rules and use the same headers as in the xls data source.

However, any columns which would contain comma separated values in a spreadsheet must have the contents delineated using a semicolon ';' character rather than commas.
In the following example, the svc_Forced services ICMP;SNMP are separated using a semicolon.

```
Node_Label,IP_Management,MgmtType_,svc_Forced,cat_Environment
bbone-gw2,10.0.23.2,P,ICMP;SNMP,Backbone
```

Example configuration for the requisition myinventory from a csv file myinventory.csv
[source,bash]
----
include::example$csv/requisitions/myinventory/requisition.properties[]
----

Example configuration for the requisition myinventory-noheaders from a csv file myinventory-noheaders.csv
This has a source.org.opennms.pris.spreadsheet.fields property set.

[source,bash]
----
include::example$csv/requisitions/myinventory-noheaders/requisition.properties[]
----
