### File: global.properties
# Generate a requisition and create a requisition file to target
# Create a file for all requisitions matching * (glob pattern)

driver = file
target = /my/output/folder
requisitions = *
