
[[script-mapper]]
=== Script mapper
This mapper is used to give you the flexibility building your own mapper without the need compiling from source.
The source uses https://www.jcp.org/en/jsr/detail?id=223[JSR-223 Scripting Engine].
The used language can be changed by setting the property `mapper.lang` in your `requisition.properties` file.
The following example runs your script in the the http://en.wikipedia.org/wiki/Rhino_%28JavaScript_engine%29[JavaScript Rhino] engine:

[source,bash]
----
### File: requisition.properties

## source configuration part
source = ...

## Run a no operation mapper
mapper = echo

# run mapper script in JavaScript
mapper.lang=javascript
mapper.file = myJavaScriptSource.js
----

If you don't set the language `lang` property the script engine tries to detect the language by evaluating the file extension.

[options="header"cols="1,^1,10"]
|========================
| Parameter     | Required | Description
| `mapper`      | *        | `script` to use JSR-223 Script Engine as source
| `mapper.file` | *        | Path to script source relative to `requisition.properties`
| `mapper.lang` |          | JSR-223 Script language by name
|========================

You can find a working example in _Groovy_ in the `configs/examples/script.mapper` directory.

In addition the any other mapper, a final script mapper can be used by specifying `script.file` in your requisition.properties` file.
The specified script will run after the configured mapper and can be used to transform the mappers output any further.

To specify the scripting language, the `script.lang` property can be used (see `mapper.lang`).
