// Allow GitHub image rendering
:imagesdir: images

[[advanced-config]]
== Advanced configuration

This section provides an overview on advanced configurations and use cases.

[[config-variables]]
=== Variables in configurations

The configuration mechanism of _PRIS_ supports basic variable substitution. 
Therefor it is possible to add properties to the `global.properties` file and reference the property values in any `requisition.properties` file.
Properties defined in the `global.properties` can be overwritten in a `requisition.properties` file.
It is also possible to use properties defined in a `requisition.properties` in a different part of the same `requisition.properties` again.
By default a implicit property `requisition` is also available in `requisition.properties`.

The following examples demonstrate the use of properties as variables in _PRIS_ configurations:

.Example configuration with properties defined in `global.properties` used in `requisition.properties`.
[source,bash]
----
### File: global.properties
# Start web server
# The web server listens on all interfaces and can be accessed on TCP port 8000
# URL: http://${your-ip}:8000/requisitions/${name-requisition-cfg}

driver = http
host = 0.0.0.0
port = 8000

httpUser = myUser
httpPassword = 987654321


### File: opennmsdemo/requisition.properties
# This example reads imports the requisition name Latency from
# the public available demo system.
source = http
source.url = http://demo.opennms.com/opennms/rest/requisitions/${requisition}
source.username = ${httpUser}
source.password = ${httpPassword}

### mapper to set asset longitude and latitude based on a surveillance category ###
mapper = script
mapper.file = setGeoInfo.groovy

----
