// Allow GitHub image rendering
:imagesdir: images

[[provision-to-opennms]]
== Provision to OpenNMS
_PRIS_ just provides requisitions in the xml format that _OpenNMS_ understands.
There is no "connection" between _PRIS_ and _OpenNMS_ by default.
To use the requisition from _PRIS_ in _OpenNMS_, _Provisiond_ has to be triggered.
There are multiple ways to trigger _Provisiond_ to pick up the requisitions from _PRIS_.


=== Provisiond scheduled ===
_Provisiond_ can be configured to provision a requisition from an `URL` on a configurable schedule.
To configure _Provisiond_ to provision a requisition from _PRIS_ via `http` a configuration entry like the following can be used.

.Configuration from OpenNMS Provisiond with provisiond-configuration.xml
[source,xml]
----
<requisition-def import-name="myRouter" import-url-resource="http://localhost:8000/requisitions/myRouter">
  <cron-schedule>0 0 0 * * ? *</cron-schedule>
</requisition-def>

<requisition-def import-name="myServer" import-url-resource="http://localhost:8000/requisitions/myServer">
  <cron-schedule>0 0 1 * * ? *</cron-schedule>
</requisition-def>
----


=== Provision via Event ===
A special _OpenNMS Event_ can be sent to _OpenNMS_ to trigger provisioning of a requisition right away.
Sending an event to _OpenNMS_ in general can be achieved via the _OpenNMS WebUI_ or the _send-event.pl_ script.
The following example demonstrates the use of _send-event.pl_ to emit the provisioning event.

.Send a provisioning event to trigger provisioning via http from _PRIS_
[source,bash]
----
./send-event.pl -p 'url http://localhost:8000/requisitions/myRouter' uei.opennms.org/internal/importer/reloadImport
----
The example assumes that _OpenNMS_ is running on the system on which _send-event.pl_ is called.
The `url` parameter references the `url` that offers the requisition via _PRIS_.
Please check the _send-event.pl_ documentation for additional information.


=== Provision via RestAPI ===
_OpenNMS_ provides an extensive `RestAPI` that covers provisioning.
Please follow the _OpenNMS RestAPI_ documentation for further information. 